skip login page for auth
DataDog/temporalio-ui pull request #5
Opened 2024-06-27 20:25 UTC by bgerrity

- **support oidc implicit flow**
- **datadog patches**
- **Update log level from fatal to error to fix cli download and start (#2057)**
- **route straight to vault**

2024-06-27 20:47 UTC, bgerrity commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/DataDog/temporalio-ui/5?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#5** <a href="https://app.graphite.dev/github/pr/DataDog/temporalio-ui/5?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#6** <a href="https://app.graphite.dev/github/pr/DataDog/temporalio-ui/6?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @bgerrity and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-27 20:51 UTC, sonalparab requested changes
I think this infinite redirects when you're not authorized, which does not work for Temporal UI for Domains i.e. https://temporal.us1.staging.dog/ for people who don't have a domain because the proxy throws an unauthorized error here: https://github.com/DataDog/dd-source/blob/main/domains/atlas/apps/apis/internal/workflowserviceproxy/workflowserviceproxy.go#L532
Could we change this to only try to autologin once?

2024-07-01 20:00 UTC, sonalparab approved these changes
lgtm, 1 future suggestion

2024-07-01 20:00 UTC, sonalparab commented on src/routes/(app)/+layout.ts
> +  }
So the very first time a user navigates to a Temporal UI for a new cluster/datacenter they will need to click the login button right? 
Would be nice if we could remove that click as well in the future (like how the Atlas UI/other internal web apps never require a login click) but that's a super small optimization so not high priority

2024-07-02 15:30 UTC, bgerrity commented
### Merge activity

* **Jul 2, 11:30 AM EDT**: @bgerrity started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/DataDog/temporalio-ui/5).

2024-07-02 15:34 UTC, merged